### ISSUE TITLE
Consider releasing Spectrum.swc for download.

### ISSUE THREAD

**Issue by blackjyn** [unhurdle/spectrum-royale#70]
Thanks for this beautiful component set.
I've tried to build myself but no luck.
Did I missing thing or doing the step wrong?

**Env:**
- Win x64
- Royale with SWF support v0.9.6
- Java 8 
- ANT v1.9.4

**config**:
- `%ROYALE_HOME` set to `path\to\apache-royale-0.9.6-bin-js-swf\royale-asjs`

**build:** 
- `npm install` , succeed as `playerglobal.swc` is downloaded.
- `ant` , return `BUILD SUCCESS` BUT no `target\Spectrum.swc` output. However I saw this probem during build:
![spectrumBuildErr](https://user-images.githubusercontent.com/6046191/93663224-57977600-fa90-11ea-9f76-a643201faca6.png)

I'd glad if you put a downloadable SWC for us (the lazy one like me. :laughing: )

**Comment by Harbs** [comment]
I'll try to upload a SWC with a link in the readme.

The reason you're having compiling issues is because Spectrum relies on Royale version 0.9.8. Until we release that, you will need to download the nightly build of Royale or build from https://github.com/unhurdle/spectrum-royale/commit/b5349fed31085210ac03f292503512b13b0c5bce or earlier.

**Comment by Harbs** [comment]
Thanks for your interest!

**Comment by blackjyn** [comment]
you're welcome
